name = "aoc_2024"
uuid = "20b7251c-fd95-440e-be11-95180ceb5ab9"
authors = ["gerben <gerry2211@gmail.com>"]
version = "0.1.0"

[deps]
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"

[compat]
Format = "1.3.7"
Match = "2.3.0"
